services:
  database:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: de-prueba
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_new_network
      
  python_app:
    build:
      context: .
      dockerfile: Dockerfile  # Asegúrate de que el nombre del archivo Dockerfile sea correcto
    networks:
      - my_new_network

volumes:
  db_data:

networks:
  my_new_network:
