version: "3.9"
services:
  #####################
  # PostgreSQL Database
  ####################
  database:
    image: postgres:15.2-alpine
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sales
    ports:
      - 5432:5432

    ##########
  # PgAdmin 
  ##########
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    depends_on:
      - database

  #########
  # Volume
  #########
volumes:
  db:
